### PR TITLE
EASY-2152 : upgrade jetty with fix for cleanup of multipart on aborted upload

### PR DESCRIPTION
**Pull request by jo-pol**
https://github.com/eclipse/jetty.project/issues/3683
https://github.com/eclipse/jetty.project/releases/tag/jetty-9.4.19.v20190610

Fixes EASY-2152 : upgrade jetty with fix for cleanup of multipart on aborted upload

#### When applied it will
* remove multipart files of aborted uploads
* 
* 

#### How should this be manually tested?

on deasy
* `watch ls -la /var/opt/dans.knaw.nl/tmp/easy-deposit-api/multipart-location/`
* upload a large file
* abort before the status bar reaches 100%
* before deploy the multipart file is not removed, after deploy it will be removed

#### Related pull requests on github
repo                       | PR                | note
-------------------------- | ----------------- | ----
easy-                      | [PR#](PRlink)     | ..

### CODE REVIEW

**Comment by rvanheest** [comment]
I've added Jetty to our dependency monitoring in Slack. Now, once a new version is released, we get an automatic notification about this.

**Comment by rvanheest** [comment]
@jo-pol not sure, but would it be possible to write a test that fails on the old dependency version but succeeds on this one? (don't spend to much time on it, though, if you can't immediately think of a nice solution!)

**Comment by jo-pol** [comment]
I'm afraid I have no inspiration for a unit test. 

The test would have to
* configure a `multipart.file-size-threshold` of zero
* monitor the files in `multipart.location`
* before a simulated interrupt some but not all bytes of the bodypart should have been saved to a file in the `multipart.location`
* another test should have multiple body parts and get interrupted somewhere after the first and before the last part was saved.

I also wonder it would test real jetty behaviour.

https://github.com/DANS-KNAW/easy-deposit-api/blob/dd284b99886f8d34fdc6717a937888b25ea8a930/src/test/scala/nl.knaw.dans.easy.deposit/servlets/UploadSpec.scala#L170-L185

**Comment by jo-pol** [comment]
Writing the phrase "I also wonder it would test real jetty behaviour": we should only write unit tests to check our own code, not test jetty-code. So even if I could, I should not.

**Pull request merged**
